# Building a Simple Neural Network ( _using tensors and its operations_ )

In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [43]:
torch.manual_seed(7)
features = torch.randn(1,5)
weights = torch.randn_like(features)
bias = torch.randn(1,1)

In [44]:
# Output using element wise multiplication of tensors
y = (features*weights).sum()+bias
y = activation(y)
print(y)

y = torch.sum(features*weights)+bias
y = activation(y)
print(y)

tensor([[0.1595]])
tensor([[0.1595]])


In [45]:
# Output using Matrix Multiplication of tensors
weights = weights.view(5,1)

# Now features : (1,5) and weights : (5,1)
# output of torch.matmul(features,weights) : (1,1)
y = torch.matmul(features,weights)+bias
y = activation(y)

print(y)

tensor([[0.1595]])


# Tensors and Storage

In [41]:
# A tensor is a view of it's 1-D storage
# Has storage_offset, shape(size) and stride properties

In [25]:
points = torch.tensor([[1,2],[3,4],[5,6]])
print(points)
print("Storage Offset :", points.storage_offset())
print("Shape :", points.shape)
print("Stride :", points.stride())
print("Storage :\n", points.storage())

tensor([[1, 2],
        [3, 4],
        [5, 6]])
Storage Offset : 0
Shape : torch.Size([3, 2])
Stride : (2, 1)
Storage :
  1
 2
 3
 4
 5
 6
[torch.LongStorage of size 6]


In [27]:
points_t = points.transpose(0,1) # or points.t() or points.transpose()
print(points_t)
print("Storage Offset :", points_t.storage_offset())
print("Shape :", points_t.shape)
print("Stride :", points_t.stride())
print("Storage :\n", points_t.storage())

# Stride of the tensor and it's transpose - get reversed (of the dimensions along which the transpose is applied)

tensor([[1, 3, 5],
        [2, 4, 6]])
Storage Offset : 0
Shape : torch.Size([2, 3])
Stride : (1, 2)
Storage :
  1
 2
 3
 4
 5
 6
[torch.LongStorage of size 6]


In [28]:
# A tensor, it's transpose, it's subtensor : all refer to the same storage

In [31]:
print(points.is_contiguous())   
print(points_t.is_contiguous())   # Since stride of the rightmost dimension is not 1

True
False


In [38]:
# To get a contiguous tensor from a non-contiguous tensor (happens by reshuffling the original storage)
points_t_cont = points_t.contiguous()
print(points_t_cont)
print("Storage Offset :", points_t_cont.storage_offset())
print("Shape :", points_t_cont.shape)
print("Stride :", points_t_cont.stride())  # Different from points_t tensor (since the storage is reshuffled)
print("Storage :\n", points_t_cont.storage())
print(id(points_t_cont.storage()) == id(points_t.storage()))  # Reshuffles the same storage

tensor([[1, 3, 5],
        [2, 4, 6]])
Storage Offset : 0
Shape : torch.Size([2, 3])
Stride : (3, 1)
Storage :
  1
 3
 5
 2
 4
 6
[torch.LongStorage of size 6]
True


In [40]:
print(points_t.is_contiguous())  # Now this becomes non-contiguous
print(points_t.stride())

False
(1, 2)


# Larger Neural Network (1 hidden layer)

In [46]:
torch.manual_seed(7)

In [47]:
features = torch.randn(1,3)

In [48]:
n_input = features.shape[1]    # number of input units
n_hidden = 2    # number of hidden units (1st and the only hidden layer here)
n_output = 1    # number of output units

In [49]:
W1 = torch.randn(n_input, n_hidden)    # weights for layer 0 (input) to layer 1 (hidden) : stacked horizontally 
W2 = torch.randn(n_hidden, n_output)   # weights for layer 1 (hidden) to layer 2 (output)

B1 = torch.randn(1,n_hidden)   # bias for hidden units : stacked horizontally
B2 = torch.randn(1,n_output)   # bias for output units

In [52]:
a1 = torch.matmul(features,W1) + B1
a1 = activation(a1)

In [53]:
a2 = torch.matmul(a1,W2) + B2
a2 = activation(a2)

In [54]:
print("Output of this multi-layer network :", a2)

Output of this multi-layer network : tensor([[0.3171]])
